XIVY-13150 implement notification actions
axonivy/dev-workflow-ui pull request #322
Opened 2024-03-15 10:16 UTC by ivy-lgi

Before:
![image](https://github.com/axonivy/dev-workflow-ui/assets/141232142/6a261408-7cd0-4d71-9a37-c40fb570a516)

After:
![image](https://github.com/axonivy/dev-workflow-ui/assets/141232142/4b685ce2-8136-439e-8881-fed872c204cf)

I noticed some issues we probably should discuss. Probably easier to explain in a meeting, but here are some notes:

Even though `WebNotification` contains a `List<WebNotificationAction>`, I assume there is exactly one `WebNotificationType.INFO` and zero or one `WebNotificationType.RUN` for now. If this changes, the implementation of the UI has to change as well. If this stays, maybe we should just provide two individual attributes for these?

In case of a list (at least for `WebNotificationType.RUN`) we could iterate over all of them and display a link/icon for each. However, I do not know what they do. All would have the same icon and the same tool tip. Another attribute like a description would be necessary for customization. To also make this language specific seems cumbersome. Maybe an `Enum` again with which the right CMS entry is acquired?

For new task notifications, I cannot easily determine whether a task has been completed or not. This means, I cannot hide the run link/icon if that is the case. Maybe we should add a method to `WebNotificationAction` that determines whether the action should be shown or not? Although, this will require information about the task to be present either in the `WebNotificationAction` or the `WebNotification` itself. 

This makes me think we should split `NotifcationAction` more precisely into something like:
```
> NotificationAction
  > InfoAction (one per Notification, in its own attribute)
  > RunnableAction (one or a list per Notification)
    > StartTaskAction
    > etc.
```

Another idea is to simply provide `WebNotification` with the `ITask` and/or `ICase`. I think this way we could completely remove the whole `NotificationAction` infrastructure again, as we then have access to all the links through that. At least for the current requirements this would be sufficient, or am I missing something?

2024-03-15 12:21 UTC, weissreto requested changes

2024-03-15 12:21 UTC, weissreto commented on dev-workflow-ui/webContent/includes/template/notifications.xhtml
> +                <h:outputText value="#{notification.message}"/>
still use escape=false if the template wants to make something <b> or color=red. etc.

2024-03-15 12:21 UTC, weissreto commented on dev-workflow-ui/webContent/includes/template/notifications.xhtml
> +              <h:outputLink id="notificationMessage" value="#{notification.infoAction.link()}" styleClass="notification-message">
Also make it optional if no info action is here only render the outputText

2024-03-15 12:21 UTC, weissreto commented on dev-workflow-ui/webContent/includes/template/notifications.xhtml
> +              <div class="p-d-flex notification-action-container">
Maybe split container to mark as read and actions container. Also add more spacing between them.

2024-03-15 12:21 UTC, weissreto commented on dev-workflow-ui/webContent/includes/template/notifications.xhtml
> +                <h:outputLink id="notificationRunAction" value="#{notification.runAction.link()}" rendered="#{notification.runAction != null}">
Iterate over all non info actions

2024-03-15 12:21 UTC, weissreto commented on dev-workflow-ui/webContent/includes/template/notifications.xhtml
> +                  <i class="notification-action si si-controls-play p-mr-1 " />
get the css icon from the action itself. The action should be a DTO that delivers different CSS icons for different kind of actions

2024-03-15 12:24 UTC, weissreto commented
> Before: ![image](https://private-user-images.githubusercontent.com/141232142/313149839-6a261408-7cd0-4d71-9a37-c40fb570a516.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MDU1ODAsIm5iZiI6MTcxMDUwNTI4MCwicGF0aCI6Ii8xNDEyMzIxNDIvMzEzMTQ5ODM5LTZhMjYxNDA4LTdjZDAtNGQ3MS05YTM3LWM0MGZiNTcwYTUxNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNVQxMjIxMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Y2UxNzIwNGRmMzVjNDU5M2M4Y2VjOTk5YTBiMjQ2MDcwZDEzNTQyYzUwOTcwMGE5YzhiZmY2ZmYwN2U2YjZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.K7K_r4ERyRPTXQ4CjFFG3wtvh27TpnPq8XImniLL9B0)
> 
> After: ![image](https://private-user-images.githubusercontent.com/141232142/313136539-4b685ce2-8136-439e-8881-fed872c204cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MDU1ODAsIm5iZiI6MTcxMDUwNTI4MCwicGF0aCI6Ii8xNDEyMzIxNDIvMzEzMTM2NTM5LTRiNjg1Y2UyLTgxMzYtNDM5ZS04ODgxLWZlZDg3MmMyMDRjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNVQxMjIxMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOWFmMTEwMTBiNDU4NTRkY2UzNDA5NGI1NzYzNWUxOWZlZTI5MzNhNGZjMTJmNGI5YWMwZDhhOTI5YjQ4OTUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pmnI8Ecw3Yf1j22Kgcdf-sedkoYTpNZtFpOqdyvdzRU)
> 
> I noticed some issues we probably should discuss. Probably easier to explain in a meeting, but here are some notes:
> 
> Even though `WebNotification` contains a `List<WebNotificationAction>`, I assume there is exactly one `WebNotificationType.INFO` and zero or one `WebNotificationType.RUN` for now. If this changes, the implementation of the UI has to change as well. If this stays, maybe we should just provide two individual attributes for these?
> 
> In case of a list (at least for `WebNotificationType.RUN`) we could iterate over all of them and display a link/icon for each. However, I do not know what they do. All would have the same icon and the same tool tip. Another attribute like a description would be necessary for customization. To also make this language specific seems cumbersome. Maybe an `Enum` again with which the right CMS entry is acquired?
> 
> For new task notifications, I cannot easily determine whether a task has been completed or not. This means, I cannot hide the run link/icon if that is the case. Maybe we should add a method to `WebNotificationAction` that determines whether the action should be shown or not? Although, this will require information about the task to be present either in the `WebNotificationAction` or the `WebNotification` itself.
> 
> This makes me think we should split `NotifcationAction` more precisely into something like:
> 
> ```
> > NotificationAction
>   > InfoAction (one per Notification, in its own attribute)
>   > RunnableAction (one or a list per Notification)
>     > StartTaskAction
>     > etc.
> ```
> 
> Another idea is to simply provide `WebNotification` with the `ITask` and/or `ICase`. I think this way we could completely remove the whole `NotificationAction` infrastructure again, as we then have access to all the links through that. At least for the current requirements this would be sufficient, or am I missing something?

Let's keep it simple. Plan a meeting with Marcel Prügel and Team WaWa for next week so that we can discuss their requirements. If they have more requirements (css icon, description, etc) we can implement them then.

The new-task event provider can decide if the task is available. We do not have to do that on the UI. If the task is already done the user gets redirected to the detail page of the task and message is displayed that it is already done. Good enough.

2024-03-15 15:42 UTC, ivy-lgi commented
Look if multiple non info actions were present:
![image](https://github.com/axonivy/dev-workflow-ui/assets/141232142/81b127d6-ebea-4611-8a4f-2a4cb6f9a825)

2024-03-18 07:35 UTC, weissreto approved these changes
Changes are good. 
On the UI I would like that actions are on the same column than other action independent of the mark as read button. Talk to @ivy-lli  how to do that. Can be implemented on another PR.

2024-03-18 07:41 UTC, merged

2024-03-18 09:04 UTC, alexsuter commented
@ivy-lgi I think this has broken the core test suite engine-integration