Add notes to task details
axonivy/dev-workflow-ui pull request #383
Opened 2024-07-23 12:15 UTC by jackra1n

Simple field showing the count of notes and opening a dialog with the notes when clicked.

Do we also want to show notes for cases?
And should I also add the possibility to add notes or only read?

![2024-07-23_14-10](https://github.com/user-attachments/assets/7cd8fbcb-6e9b-4b49-a1e4-8837cb0dc7c4)
![2024-07-23_14-11](https://github.com/user-attachments/assets/769ee29d-7986-4683-8d58-f10d87c642d1)

2024-07-23 13:06 UTC, alexsuter commented
@jackra1n don't you want to try dynamic dialogs? we support this now.

2024-07-23 13:07 UTC, jackra1n commented
> @jackra1n don't you want to try dynamic dialogs? we support this now.

Yes, @ivy-cst also told me that. I will change that 😉

2024-07-23 13:07 UTC, ivy-cst commented
> @jackra1n don't you want to try dynamic dialogs? we support this now.

Already told him :+1:

2024-07-23 13:12 UTC, alexsuter commented
![image](https://github.com/user-attachments/assets/807a22d8-9f91-4c22-ab0c-8130b6a3b4a2)

2024-07-24 09:27 UTC, jackra1n commented
![image](https://github.com/user-attachments/assets/b32b6551-4cf5-41aa-88a1-2753f3245620)
![image](https://github.com/user-attachments/assets/2dba87c1-2a2c-45bf-9e32-ff3039d4e6f1)

2024-07-24 11:48 UTC, alexsuter reviewed
Good first steps :+1:

2024-07-24 11:48 UTC, alexsuter commented on dev-workflow-ui/src/ch/ivyteam/workflowui/NotesIvyDevWfBean.java
> +public class NotesIvyDevWfBean {
there is no need anymore to use "IvyDevWf". dev-workflow-ui is running a web-jar and if somebody installs it as iar, he/she could install it in it's own application.

2024-07-24 11:48 UTC, alexsuter commented on dev-workflow-ui/src/ch/ivyteam/workflowui/tasks/TasksDetailsIvyDevWfBean.java
> +    params.put("id", Arrays.asList(selectedTask.getUuid().toString()));
List.of()

2024-07-24 11:48 UTC, alexsuter commented on dev-workflow-ui/webContent/includes/template/frame-10.xhtml
> +<!DOCTYPE html>
is this needed?

2024-07-24 11:48 UTC, alexsuter commented on dev-workflow-ui/webContent/view/notesDialog.xhtml
> +        <ui:repeat value="#{notesIvyDevWfBean.notes}" var="note">
paging?
what happens if there are 1000 notes?
with big messages?

2024-07-24 11:49 UTC, alexsuter commented on dev-workflow-ui/webContent/includes/template/frame-10.xhtml
> +<!DOCTYPE html>
I mean the hole template

2024-07-24 13:59 UTC, jackra1n commented
![image](https://github.com/user-attachments/assets/dfe6dcb1-5ceb-4b66-8b5e-845428607810)

2024-07-25 07:19 UTC, jackra1n commented
@ivy-lli because cst and als are on the beach 🏖️ 😎 you can check this when you have time

2024-07-25 07:46 UTC, ivy-lli requested changes

2024-07-25 07:46 UTC, ivy-lli commented on dev-workflow-ui/webContent/view/notesDialog.xhtml
> +</style>
correct indent

2024-07-25 07:46 UTC, ivy-lli commented on dev-workflow-ui/webContent/view/notesDialog.xhtml
> +              <div class="mb-2 text-lg">
why text-lg? I would leave it the normal size?

2024-07-25 07:46 UTC, ivy-lli commented on dev-workflow-ui/webContent/view/notesDialog.xhtml
> +            <div class="mb-2 p-2 border-solid border-round border-1 border-black-alpha-10">
I would use the `--surface-d` color. mutch better in dark mode

2024-07-25 07:46 UTC, ivy-lli commented on dev-workflow-ui/webContent/view/notesDialog.xhtml
every xhtml file in the view folder is directly accessible. So I'm able to open this file without any permission or login check if I know the id of the task: https://nightly.demo.ivyteam.io/dev-workflow-ui_notes/faces/view/dev-workflow-ui/notesDialog.xhtml?id=f5da52e8-d54e-4dd8-84d4-dd99ce413fc7
I think this is not ideal, and we should add a login check.

2024-07-25 08:43 UTC, ivy-lli commented on dev-workflow-ui/webContent/view/notesDialog.xhtml
> +      <h:form id="notesForm" styleClass="notes-form" rendered="#{notesBean.hasUserPermission()}">
why not use an f:event and redirect to login page? e.g. as you do it on the task.xhtml?
`<f:event type="preRenderView" listener="#{tasksDetailsIvyDevWfBean.redirectIfCantResume}" />`

2024-07-25 08:48 UTC, ivy-lli approved these changes
Cool stuff. 
The case notes will be part of a next PR I assume?

2024-07-25 09:05 UTC, jackra1n commented
> Cool stuff. The case notes will be part of a next PR I assume?

Yes I think I will do that as I think it should be pretty quick job, even tho Im not sure we were talking with Christian about case notes

2024-07-25 09:06 UTC, ivy-lli commented
> > Cool stuff. The case notes will be part of a next PR I assume?
> 
> Yes I think I will do that as I think it should be pretty quick job, even tho Im not sure we were talking with Christian about case notes

https://github.com/axonivy/dev-workflow-ui/pull/383#issuecomment-2245141707

2024-07-25 09:07 UTC, jackra1n commented
> > > Cool stuff. The case notes will be part of a next PR I assume?
> > 
> > 
> > Yes I think I will do that as I think it should be pretty quick job, even tho Im not sure we were talking with Christian about case notes
> 
> [#383 (comment)](https://github.com/axonivy/dev-workflow-ui/pull/383#issuecomment-2245141707)

ohh thanks haha 😅

2024-07-25 09:07 UTC, merged